using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Battleship_Rebuild
{
    class GameSession
    {
        public void DrawGameBoard()
        {
            Coordinate PA1 = new Coordinate();
            PA1.Gfx = ".";
            PA1.index = 1;
            Coordinate PB1 = new Coordinate();
            PB1.Gfx = ".";
            PB1.index = 2;
            Coordinate PC1 = new Coordinate();
            PC1.Gfx = ".";
            PC1.index = 3;
            Coordinate PD1 = new Coordinate();
            PD1.Gfx = ".";
            PD1.index = 4;
            Coordinate PE1 = new Coordinate();
            PE1.Gfx = ".";
            PE1.index = 5;
            Coordinate PF1 = new Coordinate();
            PF1.Gfx = ".";
            PF1.index = 6;
            Coordinate PG1 = new Coordinate();
            PG1.Gfx = ".";
            PG1.index = 7;
            Coordinate PH1 = new Coordinate();
            PH1.Gfx = ".";
            PH1.index = 8;
            Coordinate PI1 = new Coordinate();
            PI1.Gfx = ".";
            PI1.index = 9;
            Coordinate PJ1 = new Coordinate();
            PJ1.Gfx = ".";
            PJ1.index = 10;

            Coordinate PA2 = new Coordinate();
            PA2.Gfx = ".";
            PA2.index = 11;
            Coordinate PB2 = new Coordinate();
            PB2.Gfx = ".";
            PB2.index = 12;
            Coordinate PC2 = new Coordinate();
            PC2.Gfx = ".";
            PC2.index = 13;
            Coordinate PD2 = new Coordinate();
            PD2.Gfx = ".";
            PD2.index = 14;
            Coordinate PE2 = new Coordinate();
            PE2.Gfx = ".";
            PE2.index = 15;
            Coordinate PF2 = new Coordinate();
            PF2.Gfx = ".";
            PF2.index = 16;
            Coordinate PG2 = new Coordinate();
            PG2.Gfx = ".";
            PG2.index = 17;
            Coordinate PH2 = new Coordinate();
            PH2.Gfx = ".";
            PH2.index = 18;
            Coordinate PI2 = new Coordinate();
            PI2.Gfx = ".";
            PI2.index = 19;
            Coordinate PJ2 = new Coordinate();
            PJ2.Gfx = ".";
            PJ2.index = 20;

            Coordinate PA3 = new Coordinate();
            PA3.Gfx = ".";
            PA3.index = 21;
            Coordinate PB3 = new Coordinate();
            PB3.Gfx = ".";
            PB3.index = 22;
            Coordinate PC3 = new Coordinate();
            PC3.Gfx = ".";
            PC3.index = 23;
            Coordinate PD3 = new Coordinate();
            PD3.Gfx = ".";
            PD3.index = 24;
            Coordinate PE3 = new Coordinate();
            PE3.Gfx = ".";
            PE3.index = 25;
            Coordinate PF3 = new Coordinate();
            PF3.Gfx = ".";
            PF3.index = 26;
            Coordinate PG3 = new Coordinate();
            PG3.Gfx = ".";
            PG3.index = 27;
            Coordinate PH3 = new Coordinate();
            PH3.Gfx = ".";
            PH3.index = 28;
            Coordinate PI3 = new Coordinate();
            PI3.Gfx = ".";
            PI3.index = 29;
            Coordinate PJ3 = new Coordinate();
            PJ3.Gfx = ".";
            PJ3.index = 30;

            Coordinate PA4 = new Coordinate();
            PA4.Gfx = ".";
            PA4.index = 31;
            Coordinate PB4 = new Coordinate();
            PB4.Gfx = ".";
            PB4.index = 32;
            Coordinate PC4 = new Coordinate();
            PC4.Gfx = ".";
            PC4.index = 33;
            Coordinate PD4 = new Coordinate();
            PD4.Gfx = ".";
            PD4.index = 34;
            Coordinate PE4 = new Coordinate();
            PE4.Gfx = ".";
            PE4.index = 35;
            Coordinate PF4 = new Coordinate();
            PF4.Gfx = ".";
            PF4.index = 36;
            Coordinate PG4 = new Coordinate();
            PG4.Gfx = ".";
            PG4.index = 37;
            Coordinate PH4 = new Coordinate();
            PH4.Gfx = ".";
            PH4.index = 38;
            Coordinate PI4 = new Coordinate();
            PI4.Gfx = ".";
            PI4.index = 39;
            Coordinate PJ4 = new Coordinate();
            PJ4.Gfx = ".";
            PJ4.index = 40;

            Coordinate PA5 = new Coordinate();
            PA5.Gfx = ".";
            PA5.index = 41;
            Coordinate PB5 = new Coordinate();
            PB5.Gfx = ".";
            PB5.index = 42;
            Coordinate PC5 = new Coordinate();
            PC5.Gfx = ".";
            PC5.index = 43;
            Coordinate PD5 = new Coordinate();
            PD5.Gfx = ".";
            PD5.index = 44;
            Coordinate PE5 = new Coordinate();
            PE5.Gfx = ".";
            PE5.index = 45;
            Coordinate PF5 = new Coordinate();
            PF5.Gfx = ".";
            PF5.index = 46;
            Coordinate PG5 = new Coordinate();
            PG5.Gfx = ".";
            PG5.index = 47;
            Coordinate PH5 = new Coordinate();
            PH5.Gfx = ".";
            PH5.index = 48;
            Coordinate PI5 = new Coordinate();
            PI5.Gfx = ".";
            PI5.index = 49;
            Coordinate PJ5 = new Coordinate();
            PJ5.Gfx = ".";
            PJ5.index = 50;

            Coordinate PA6 = new Coordinate();
            PA6.Gfx = ".";
            PA6.index = 51;
            Coordinate PB6 = new Coordinate();
            PB6.Gfx = ".";
            PB6.index = 52;
            Coordinate PC6 = new Coordinate();
            PC6.Gfx = ".";
            PC6.index = 53;
            Coordinate PD6 = new Coordinate();
            PD6.Gfx = ".";
            PD6.index = 54;
            Coordinate PE6 = new Coordinate();
            PE6.Gfx = ".";
            PE6.index = 55;
            Coordinate PF6 = new Coordinate();
            PF6.Gfx = ".";
            PF6.index = 56;
            Coordinate PG6 = new Coordinate();
            PG6.Gfx = ".";
            PG6.index = 57;
            Coordinate PH6 = new Coordinate();
            PH6.Gfx = ".";
            PH6.index = 58;
            Coordinate PI6 = new Coordinate();
            PI6.Gfx = ".";
            PI6.index = 59;
            Coordinate PJ6 = new Coordinate();
            PJ6.Gfx = ".";
            PJ6.index = 60;

            Coordinate PA7 = new Coordinate();
            PA7.Gfx = ".";
            PA7.index = 61;
            Coordinate PB7 = new Coordinate();
            PB7.Gfx = ".";
            PB7.index = 62;
            Coordinate PC7 = new Coordinate();
            PC7.Gfx = ".";
            PC7.index = 63;
            Coordinate PD7 = new Coordinate();
            PD7.Gfx = ".";
            PD7.index = 64;
            Coordinate PE7 = new Coordinate();
            PE7.Gfx = ".";
            PE7.index = 65;
            Coordinate PF7 = new Coordinate();
            PF7.Gfx = ".";
            PF7.index = 66;
            Coordinate PG7 = new Coordinate();
            PG7.Gfx = ".";
            PG7.index = 67;
            Coordinate PH7 = new Coordinate();
            PH7.Gfx = ".";
            PH7.index = 68;
            Coordinate PI7 = new Coordinate();
            PI7.Gfx = ".";
            PI7.index = 69;
            Coordinate PJ7 = new Coordinate();
            PJ7.Gfx = ".";
            PJ7.index = 70;

            Coordinate PA8 = new Coordinate();
            PA8.Gfx = ".";
            PA8.index = 71;
            Coordinate PB8 = new Coordinate();
            PB8.Gfx = ".";
            PB8.index = 72;
            Coordinate PC8 = new Coordinate();
            PC8.Gfx = ".";
            PC8.index = 73;
            Coordinate PD8 = new Coordinate();
            PD8.Gfx = ".";
            PD8.index = 74;
            Coordinate PE8 = new Coordinate();
            PE8.Gfx = ".";
            PE8.index = 75;
            Coordinate PF8 = new Coordinate();
            PF8.Gfx = ".";
            PF8.index = 76;
            Coordinate PG8 = new Coordinate();
            PG8.Gfx = ".";
            PG8.index = 77;
            Coordinate PH8 = new Coordinate();
            PH8.Gfx = ".";
            PH8.index = 78;
            Coordinate PI8 = new Coordinate();
            PI8.Gfx = ".";
            PI8.index = 79;
            Coordinate PJ8 = new Coordinate();
            PJ8.Gfx = ".";
            PJ8.index = 80;

            Coordinate PA9 = new Coordinate();
            PA9.Gfx = ".";
            PA9.index = 81;
            Coordinate PB9 = new Coordinate();
            PB9.Gfx = ".";
            PB9.index = 82;
            Coordinate PC9 = new Coordinate();
            PC9.Gfx = ".";
            PC9.index = 83;
            Coordinate PD9 = new Coordinate();
            PD9.Gfx = ".";
            PD9.index = 84;
            Coordinate PE9 = new Coordinate();
            PE9.Gfx = ".";
            PE9.index = 85;
            Coordinate PF9 = new Coordinate();
            PF9.Gfx = ".";
            PF9.index = 86;
            Coordinate PG9 = new Coordinate();
            PG9.Gfx = ".";
            PG9.index = 87;
            Coordinate PH9 = new Coordinate();
            PH9.Gfx = ".";
            PH9.index = 88;
            Coordinate PI9 = new Coordinate();
            PI9.Gfx = ".";
            PI9.index = 89;
            Coordinate PJ9 = new Coordinate();
            PJ9.Gfx = ".";
            PJ9.index = 90;

            Coordinate PA10 = new Coordinate();
            PA10.Gfx = ".";
            PA10.index = 91;
            Coordinate PB10 = new Coordinate();
            PB10.Gfx = ".";
            PB10.index = 92;
            Coordinate PC10 = new Coordinate();
            PC10.Gfx = ".";
            PC10.index = 93;
            Coordinate PD10 = new Coordinate();
            PD10.Gfx = ".";
            PD10.index = 94;
            Coordinate PE10 = new Coordinate();
            PE10.Gfx = ".";
            PE10.index = 95;
            Coordinate PF10 = new Coordinate();
            PF10.Gfx = ".";
            PF10.index = 96;
            Coordinate PG10 = new Coordinate();
            PG10.Gfx = ".";
            PG10.index = 97;
            Coordinate PH10 = new Coordinate();
            PH10.Gfx = ".";
            PH10.index = 98;
            Coordinate PI10 = new Coordinate();
            PI10.Gfx = ".";
            PI10.index = 99;
            Coordinate PJ10 = new Coordinate();
            PJ10.Gfx = ".";
            PJ10.index = 100;

            Coordinate EA1 = new Coordinate();
            EA1.Gfx = ".";
            EA1.index = 201;
            Coordinate EB1 = new Coordinate();
            EB1.Gfx = ".";
            EB1.index = 202;
            Coordinate EC1 = new Coordinate();
            EC1.Gfx = ".";
            EC1.index = 203;
            Coordinate ED1 = new Coordinate();
            ED1.Gfx = ".";
            ED1.index = 204;
            Coordinate EE1 = new Coordinate();
            EE1.Gfx = ".";
            EE1.index = 205;
            Coordinate EF1 = new Coordinate();
            EF1.Gfx = ".";
            EF1.index = 206;
            Coordinate EG1 = new Coordinate();
            EG1.Gfx = ".";
            PB1.index = 207;
            Coordinate EH1 = new Coordinate();
            EH1.Gfx = ".";
            EH1.index = 208;
            Coordinate EI1 = new Coordinate();
            EI1.Gfx = ".";
            EI1.index = 209;
            Coordinate EJ1 = new Coordinate();
            EJ1.Gfx = ".";
            EJ1.index = 210;

            Coordinate EA2 = new Coordinate();
            EA2.Gfx = ".";
            EA2.index = 211;
            Coordinate EB2 = new Coordinate();
            EB2.Gfx = ".";
            EB2.index = 212;
            Coordinate EC2 = new Coordinate();
            EC2.Gfx = ".";
            EC2.index = 213;
            Coordinate ED2 = new Coordinate();
            ED2.Gfx = ".";
            ED2.index = 214;
            Coordinate EE2 = new Coordinate();
            EE2.Gfx = ".";
            EE2.index = 215;
            Coordinate EF2 = new Coordinate();
            EF2.Gfx = ".";
            EF2.index = 216;
            Coordinate EG2 = new Coordinate();
            EG2.Gfx = ".";
            EG2.index = 217;
            Coordinate EH2 = new Coordinate();
            EH2.Gfx = ".";
            EH2.index = 218;
            Coordinate EI2 = new Coordinate();
            EI2.Gfx = ".";
            EI2.index = 219;
            Coordinate EJ2 = new Coordinate();
            EJ2.Gfx = ".";
            EJ2.index = 220;

            Coordinate EA3 = new Coordinate();
            EA3.Gfx = ".";
            EA3.index = 221;
            Coordinate EB3 = new Coordinate();
            EB3.Gfx = ".";
            EB3.index = 222;
            Coordinate EC3 = new Coordinate();
            EC3.Gfx = ".";
            EC3.index = 223;
            Coordinate ED3 = new Coordinate();
            ED3.Gfx = ".";
            ED3.index = 224;
            Coordinate EE3 = new Coordinate();
            EE3.Gfx = ".";
            EE3.index = 225;
            Coordinate EF3 = new Coordinate();
            EF3.Gfx = ".";
            EF3.index = 226;
            Coordinate EG3 = new Coordinate();
            EG3.Gfx = ".";
            EG3.index = 227;
            Coordinate EH3 = new Coordinate();
            EH3.Gfx = ".";
            EH3.index = 228;
            Coordinate EI3 = new Coordinate();
            EI3.Gfx = ".";
            EI3.index = 229;
            Coordinate EJ3 = new Coordinate();
            EJ3.Gfx = ".";
            EJ3.index = 230;

            Coordinate EA4 = new Coordinate();
            EA4.Gfx = ".";
            EA4.index = 231;
            Coordinate EB4 = new Coordinate();
            EB4.Gfx = ".";
            EB4.index = 232;
            Coordinate EC4 = new Coordinate();
            EC4.Gfx = ".";
            EC4.index = 233;
            Coordinate ED4 = new Coordinate();
            ED4.Gfx = ".";
            ED4.index = 234;
            Coordinate EE4 = new Coordinate();
            EE4.Gfx = ".";
            EE4.index = 235;
            Coordinate EF4 = new Coordinate();
            EF4.Gfx = ".";
            EF4.index = 236;
            Coordinate EG4 = new Coordinate();
            EG4.Gfx = ".";
            EG4.index = 237;
            Coordinate EH4 = new Coordinate();
            EH4.Gfx = ".";
            EH4.index = 238;
            Coordinate EI4 = new Coordinate();
            EI4.Gfx = ".";
            EI4.index = 239;
            Coordinate EJ4 = new Coordinate();
            EJ4.Gfx = ".";
            EJ4.index = 240;

            Coordinate EA5 = new Coordinate();
            EA5.Gfx = ".";
            EA5.index = 241;
            Coordinate EB5 = new Coordinate();
            EB5.Gfx = ".";
            EB5.index = 242;
            Coordinate EC5 = new Coordinate();
            EC5.Gfx = ".";
            EC5.index = 243;
            Coordinate ED5 = new Coordinate();
            ED5.Gfx = ".";
            ED5.index = 244;
            Coordinate EE5 = new Coordinate();
            EE5.Gfx = ".";
            EE5.index = 245;
            Coordinate EF5 = new Coordinate();
            EF5.Gfx = ".";
            EF5.index = 246;
            Coordinate EG5 = new Coordinate();
            EG5.Gfx = ".";
            EG5.index = 247;
            Coordinate EH5 = new Coordinate();
            EH5.Gfx = ".";
            EH5.index = 248;
            Coordinate EI5 = new Coordinate();
            EI5.Gfx = ".";
            EI5.index = 249;
            Coordinate EJ5 = new Coordinate();
            EJ5.Gfx = ".";
            EJ5.index = 250;

            Coordinate EA6 = new Coordinate();
            EA6.Gfx = ".";
            EA6.index = 251;
            Coordinate EB6 = new Coordinate();
            EB6.Gfx = ".";
            EB6.index = 252;
            Coordinate EC6 = new Coordinate();
            EC6.Gfx = ".";
            EC6.index = 253;
            Coordinate ED6 = new Coordinate();
            ED6.Gfx = ".";
            ED6.index = 254;
            Coordinate EE6 = new Coordinate();
            EE6.Gfx = ".";
            EE6.index = 255;
            Coordinate EF6 = new Coordinate();
            EF6.Gfx = ".";
            EF6.index = 256;
            Coordinate EG6 = new Coordinate();
            EG6.Gfx = ".";
            EG6.index = 257;
            Coordinate EH6 = new Coordinate();
            EH6.Gfx = ".";
            EH6.index = 258;
            Coordinate EI6 = new Coordinate();
            EI6.Gfx = ".";
            EI6.index = 259;
            Coordinate EJ6 = new Coordinate();
            EJ6.Gfx = ".";
            EJ6.index = 260;

            Coordinate EA7 = new Coordinate();
            EA7.Gfx = ".";
            EA7.index = 261;
            Coordinate EB7 = new Coordinate();
            EB7.Gfx = ".";
            EB7.index = 262;
            Coordinate EC7 = new Coordinate();
            EC7.Gfx = ".";
            EC7.index = 263;
            Coordinate ED7 = new Coordinate();
            ED7.Gfx = ".";
            ED7.index = 264;
            Coordinate EE7 = new Coordinate();
            EE7.Gfx = ".";
            EE7.index = 265;
            Coordinate EF7 = new Coordinate();
            EF7.Gfx = ".";
            EF7.index = 266;
            Coordinate EG7 = new Coordinate();
            EG7.Gfx = ".";
            EG7.index = 267;
            Coordinate EH7 = new Coordinate();
            EH7.Gfx = ".";
            EH7.index = 268;
            Coordinate EI7 = new Coordinate();
            EI7.Gfx = ".";
            EI7.index = 269;
            Coordinate EJ7 = new Coordinate();
            EJ7.Gfx = ".";
            EJ7.index = 270;

            Coordinate EA8 = new Coordinate();
            EA8.Gfx = ".";
            EA8.index = 271;
            Coordinate EB8 = new Coordinate();
            EB8.Gfx = ".";
            EB8.index = 272;
            Coordinate EC8 = new Coordinate();
            EC8.Gfx = ".";
            EC8.index = 273;
            Coordinate ED8 = new Coordinate();
            ED8.Gfx = ".";
            ED8.index = 274;
            Coordinate EE8 = new Coordinate();
            EE8.Gfx = ".";
            EE8.index = 275;
            Coordinate EF8 = new Coordinate();
            EF8.Gfx = ".";
            EF8.index = 276;
            Coordinate EG8 = new Coordinate();
            EG8.Gfx = ".";
            EG8.index = 277;
            Coordinate EH8 = new Coordinate();
            EH8.Gfx = ".";
            EH8.index = 278;
            Coordinate EI8 = new Coordinate();
            EI8.Gfx = ".";
            EI8.index = 279;
            Coordinate EJ8 = new Coordinate();
            EJ8.Gfx = ".";
            EJ8.index = 280;

            Coordinate EA9 = new Coordinate();
            EA9.Gfx = ".";
            EA9.index = 281;
            Coordinate EB9 = new Coordinate();
            EB9.Gfx = ".";
            EB9.index = 282;
            Coordinate EC9 = new Coordinate();
            EC9.Gfx = ".";
            EC9.index = 283;
            Coordinate ED9 = new Coordinate();
            ED9.Gfx = ".";
            ED9.index = 284;
            Coordinate EE9 = new Coordinate();
            EE9.Gfx = ".";
            EE9.index = 285;
            Coordinate EF9 = new Coordinate();
            EF9.Gfx = ".";
            EF9.index = 286;
            Coordinate EG9 = new Coordinate();
            EG9.Gfx = ".";
            EG9.index = 287;
            Coordinate EH9 = new Coordinate();
            EH9.Gfx = ".";
            EH9.index = 288;
            Coordinate EI9 = new Coordinate();
            EI9.Gfx = ".";
            EI9.index = 289;
            Coordinate EJ9 = new Coordinate();
            EJ9.Gfx = ".";
            EJ9.index = 290;

            Coordinate EA10 = new Coordinate();
            EA10.Gfx = ".";
            EA10.index = 291;
            Coordinate EB10 = new Coordinate();
            EB10.Gfx = ".";
            EB10.index = 292;
            Coordinate EC10 = new Coordinate();
            EC10.Gfx = ".";
            EC10.index = 293;
            Coordinate ED10 = new Coordinate();
            ED10.Gfx = ".";
            ED10.index = 294;
            Coordinate EE10 = new Coordinate();
            EE10.Gfx = ".";
            EE10.index = 295;
            Coordinate EF10 = new Coordinate();
            EF10.Gfx = ".";
            EF10.index = 296;
            Coordinate EG10 = new Coordinate();
            EG10.Gfx = ".";
            EG10.index = 297;
            Coordinate EH10 = new Coordinate();
            EH10.Gfx = ".";
            EH10.index = 298;
            Coordinate EI10 = new Coordinate();
            EI10.Gfx = ".";
            EI10.index = 299;
            Coordinate EJ10 = new Coordinate();
            EJ10.Gfx = ".";
            EJ10.index = 300;

            bool SessionRunning = true;
            while (SessionRunning == true)
            {
                Console.Clear();
                Console.SetCursorPosition(0, 0);
                //Declaration for initial board drawing. These strings will be changed as the game commences.

                Console.WriteLine("\n\n\n");
                Console.WriteLine("    *****************************************************************************************");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    ** Battleship v.1               Programmer: M. Strong             Last Edit: 10/28/16  **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    *****************************************************************************************");
                Console.WriteLine("    **        PLAYER FLEET                                            ENEMY FLEET          **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **      A B C D E F G H I J                                    A B C D E F G H I J     **");
                Console.WriteLine("    **     ____________________                                   ____________________     **");
                Console.WriteLine("    **   1| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 1| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA1.Gfx, PB1.Gfx, PC1.Gfx, PD1.Gfx, PE1.Gfx, PF1.Gfx, PG1.Gfx, PH1.Gfx, PI1.Gfx, PJ1.Gfx, EA1.Gfx, EB1.Gfx, EC1.Gfx, ED1.Gfx, EE1.Gfx, EF1.Gfx, EG1.Gfx, EH1.Gfx, EI1.Gfx, EJ1.Gfx);
                Console.WriteLine("    **   2| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 2| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA2.Gfx, PB2.Gfx, PC2.Gfx, PD2.Gfx, PE2.Gfx, PF2.Gfx, PG2.Gfx, PH2.Gfx, PI2.Gfx, PJ2.Gfx, EA2.Gfx, EB2.Gfx, EC2.Gfx, ED2.Gfx, EE2.Gfx, EF2.Gfx, EG2.Gfx, EH2.Gfx, EI2.Gfx, EJ2.Gfx);
                Console.WriteLine("    **   3| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 3| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA3.Gfx, PB3.Gfx, PC3.Gfx, PD3.Gfx, PE3.Gfx, PF3.Gfx, PG3.Gfx, PH3.Gfx, PI3.Gfx, PJ3.Gfx, EA3.Gfx, EB3.Gfx, EC3.Gfx, ED3.Gfx, EE3.Gfx, EF3.Gfx, EG3.Gfx, EH3.Gfx, EI3.Gfx, EJ3.Gfx);
                Console.WriteLine("    **   4| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 4| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA4.Gfx, PB4.Gfx, PC4.Gfx, PD4.Gfx, PE4.Gfx, PF4.Gfx, PG4.Gfx, PH4.Gfx, PI4.Gfx, PJ4.Gfx, EA4.Gfx, EB4.Gfx, EC4.Gfx, ED4.Gfx, EE4.Gfx, EF4.Gfx, EG4.Gfx, EH4.Gfx, EI4.Gfx, EJ4.Gfx);
                Console.WriteLine("    **   5| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 5| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA5.Gfx, PB5.Gfx, PC5.Gfx, PD5.Gfx, PE5.Gfx, PF5.Gfx, PG5.Gfx, PH5.Gfx, PI5.Gfx, PJ5.Gfx, EA5.Gfx, EB5.Gfx, EC5.Gfx, ED5.Gfx, EE5.Gfx, EF5.Gfx, EG5.Gfx, EH5.Gfx, EI5.Gfx, EJ5.Gfx);
                Console.WriteLine("    **   6| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 6| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA6.Gfx, PB6.Gfx, PC6.Gfx, PD6.Gfx, PE6.Gfx, PF6.Gfx, PG6.Gfx, PH6.Gfx, PI6.Gfx, PJ6.Gfx, EA6.Gfx, EB6.Gfx, EC6.Gfx, ED6.Gfx, EE6.Gfx, EF6.Gfx, EG6.Gfx, EH6.Gfx, EI6.Gfx, EJ6.Gfx);
                Console.WriteLine("    **   7| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 7| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA7.Gfx, PB7.Gfx, PC7.Gfx, PD7.Gfx, PE7.Gfx, PF7.Gfx, PG7.Gfx, PH7.Gfx, PI7.Gfx, PJ7.Gfx, EA7.Gfx, EB7.Gfx, EC7.Gfx, ED7.Gfx, EE7.Gfx, EF7.Gfx, EG7.Gfx, EH7.Gfx, EI7.Gfx, EJ7.Gfx);
                Console.WriteLine("    **   8| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 8| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA8.Gfx, PB8.Gfx, PC8.Gfx, PD8.Gfx, PE8.Gfx, PF8.Gfx, PG8.Gfx, PH8.Gfx, PI8.Gfx, PJ8.Gfx, EA8.Gfx, EB8.Gfx, EC8.Gfx, ED8.Gfx, EE8.Gfx, EF8.Gfx, EG8.Gfx, EH8.Gfx, EI8.Gfx, EJ8.Gfx);
                Console.WriteLine("    **   9| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                 9| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA9.Gfx, PB9.Gfx, PC9.Gfx, PD9.Gfx, PE9.Gfx, PF9.Gfx, PG9.Gfx, PH9.Gfx, PI9.Gfx, PJ9.Gfx, EA9.Gfx, EB9.Gfx, EC9.Gfx, ED9.Gfx, EE9.Gfx, EF9.Gfx, EG9.Gfx, EH9.Gfx, EI9.Gfx, EJ9.Gfx);
                Console.WriteLine("    **  10| {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}                                10| {10} {11} {12} {13} {14} {15} {16} {17} {18} {19}     **", PA10.Gfx, PB10.Gfx, PC10.Gfx, PD10.Gfx, PE10.Gfx, PF10.Gfx, PG10.Gfx, PH10.Gfx, PI10.Gfx, PJ10.Gfx, EA10.Gfx, EB10.Gfx, EC10.Gfx, ED10.Gfx, EE10.Gfx, EF10.Gfx, EG10.Gfx, EH10.Gfx, EI10.Gfx, EJ10.Gfx);
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    **                                                                                     **");
                Console.WriteLine("    *****************************************************************************************");

                string move = Console.ReadLine();
                if (move == "A1")
                {
                    EA1.Gfx = "X";
                }

            }
        }
    }
}
